import type { LucideIcon } from 'lucide-vue-next'
import {
  AlertCircle,
  AlertTriangle,
  AlignCenter,
  AlignLeft,
  AlignRight,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  BarChart2,
  BarChart3,
  BookOpen,
  Box,
  Briefcase,
  Building2,
  Calculator,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsUp,
  Circle,
  CircleCheck,
  Clipboard,
  Clock,
  Clock3,
  Columns3,
  Copy,
  CopyPlus,
  Cpu,
  Crosshair,
  Download,
  EllipsisVertical,
  Euro,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileStack,
  FileText,
  Folder,
  FolderPlus,
  Gauge,
  Gem,
  Gift,
  GitBranch,
  GitBranchPlus,
  Github,
  Globe,
  GripVertical,
  Handshake,
  Hash,
  History,
  House,
  Image,
  Inbox,
  KeyRound,
  Languages,
  Layers,
  LayoutGrid,
  LayoutList,
  Lightbulb,
  Link,
  ListChecks,
  ListTree,
  Loader,
  LoaderCircle,
  LogOut,
  Mail,
  MapPin,
  Maximize,
  Maximize2,
  MessageSquare,
  Minus,
  Monitor,
  MoreHorizontal,
  NotebookPen,
  Package,
  PackageCheck,
  Paperclip,
  PenLine,
  Pencil,
  Phone,
  Pin,
  PinOff,
  Play,
  PlayCircle,
  Plug,
  Plus,
  PlusCircle,
  Printer,
  Puzzle,
  ReceiptText,
  Redo2,
  RefreshCw,
  Repeat,
  Rewind,
  ScrollText,
  Search,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  Sparkles,
  Square,
  Star,
  Tag,
  Terminal,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Undo,
  Undo2,
  Upload,
  UploadCloud,
  User,
  UserPlus,
  Users,
  X,
  XCircle,
  Zap,
} from 'lucide-vue-next'

export const appIcons: Record<string, LucideIcon> = {
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'align-center': AlignCenter,
  'align-left': AlignLeft,
  'align-right': AlignRight,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-up-down': ArrowUpDown,
  'bar-chart-2': BarChart2,
  'bar-chart-3': BarChart3,
  'book-open': BookOpen,
  'box': Box,
  'briefcase': Briefcase,
  'building-2': Building2,
  'calculator': Calculator,
  'check': Check,
  'check-circle': CheckCircle,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-down': ChevronsDown,
  'chevrons-up': ChevronsUp,
  'circle': Circle,
  'circle-check': CircleCheck,
  'clipboard': Clipboard,
  'clock': Clock,
  'clock-3': Clock3,
  'columns-3': Columns3,
  'copy': Copy,
  'copy-plus': CopyPlus,
  'cpu': Cpu,
  'crosshair': Crosshair,
  'download': Download,
  'ellipsis-vertical': EllipsisVertical,
  'euro': Euro,
  'external-link': ExternalLink,
  'eye': Eye,
  'eye-off': EyeOff,
  'file': File,
  'file-stack': FileStack,
  'file-text': FileText,
  'folder': Folder,
  'folder-plus': FolderPlus,
  'gauge': Gauge,
  'gem': Gem,
  'gift': Gift,
  'git-branch': GitBranch,
  'git-branch-plus': GitBranchPlus,
  'github': Github,
  'globe': Globe,
  'grip-vertical': GripVertical,
  'handshake': Handshake,
  'hash': Hash,
  'history': History,
  'house': House,
  'image': Image,
  'inbox': Inbox,
  'key-round': KeyRound,
  'languages': Languages,
  'layers': Layers,
  'layout-grid': LayoutGrid,
  'layout-list': LayoutList,
  'lightbulb': Lightbulb,
  'link': Link,
  'list-checks': ListChecks,
  'list-tree': ListTree,
  'loader': Loader,
  'loader-circle': LoaderCircle,
  'log-out': LogOut,
  'mail': Mail,
  'map-pin': MapPin,
  'maximize': Maximize,
  'maximize-2': Maximize2,
  'message-square': MessageSquare,
  'minus': Minus,
  'monitor': Monitor,
  'more-horizontal': MoreHorizontal,
  'notebook-pen': NotebookPen,
  'package': Package,
  'package-check': PackageCheck,
  'paperclip': Paperclip,
  'pen-line': PenLine,
  'pencil': Pencil,
  'phone': Phone,
  'pin': Pin,
  'pin-off': PinOff,
  'play': Play,
  'play-circle': PlayCircle,
  'plug': Plug,
  'plus': Plus,
  'plus-circle': PlusCircle,
  'printer': Printer,
  'puzzle': Puzzle,
  'receipt-text': ReceiptText,
  'redo-2': Redo2,
  'refresh-cw': RefreshCw,
  'repeat': Repeat,
  'rewind': Rewind,
  'scroll-text': ScrollText,
  'search': Search,
  'server': Server,
  'settings': Settings,
  'shield': Shield,
  'shield-check': ShieldCheck,
  'sparkles': Sparkles,
  'square': Square,
  'star': Star,
  'tag': Tag,
  'terminal': Terminal,
  'trash-2': Trash2,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  'undo': Undo,
  'undo-2': Undo2,
  'upload': Upload,
  'upload-cloud': UploadCloud,
  'user': User,
  'user-plus': UserPlus,
  'users': Users,
  'x': X,
  'x-circle': XCircle,
  'zap': Zap,
}
