#!/usr/bin/env bash
# PAI-667 — generate local, AGE-encrypted env for normal-login debug users.
# The generated passwords are never printed. The plaintext env stays under
# .local/ with 0600 permissions so dev-up can source it; the AGE copy is the
# portable local backup.

set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
LOCAL_DIR="${PAIMOS_DEBUG_ACCOUNTS_DIR:-$ROOT/.local}"
ENV_FILE="${PAIMOS_DEBUG_ACCOUNTS_ENV_FILE:-$LOCAL_DIR/debug-accounts.env}"
AGE_FILE="${PAIMOS_DEBUG_ACCOUNTS_AGE_FILE:-$LOCAL_DIR/debug-accounts.env.age}"
IDENTITY_FILE="${PAIMOS_DEBUG_ACCOUNTS_AGE_IDENTITY:-$LOCAL_DIR/debug-accounts.agekey}"
RECIPIENT_FILE="${PAIMOS_DEBUG_ACCOUNTS_AGE_RECIPIENT_FILE:-$LOCAL_DIR/debug-accounts.age.pub}"
ROTATE=0

for arg in "$@"; do
  case "$arg" in
    --rotate) ROTATE=1 ;;
    -h|--help)
      cat <<EOF
Usage: scripts/dev-debug-accounts.sh [--rotate]

Creates:
  $ENV_FILE
  $AGE_FILE

Set PAIMOS_DEBUG_ACCOUNTS_AGE_RECIPIENT to encrypt for an existing AGE
recipient. If omitted, a local AGE identity is created at:
  $IDENTITY_FILE
EOF
      exit 0
      ;;
    *)
      echo "error: unknown argument: $arg" >&2
      exit 1
      ;;
  esac
done

need() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "error: $1 is required" >&2
    exit 1
  fi
}

need age
need age-keygen
need openssl

mkdir -p "$LOCAL_DIR"
chmod 700 "$LOCAL_DIR"
umask 077

recipient="${PAIMOS_DEBUG_ACCOUNTS_AGE_RECIPIENT:-}"
if [[ -z "$recipient" ]]; then
  if [[ ! -f "$IDENTITY_FILE" ]]; then
    age-keygen -o "$IDENTITY_FILE" >/dev/null 2>&1
    chmod 600 "$IDENTITY_FILE"
  fi
  age-keygen -y "$IDENTITY_FILE" > "$RECIPIENT_FILE"
  chmod 600 "$RECIPIENT_FILE"
  recipient=$(<"$RECIPIENT_FILE")
fi

password() {
  openssl rand -base64 48 | tr -d '\n'
}

if [[ -f "$ENV_FILE" && "$ROTATE" != "1" ]]; then
  echo "debug account env already exists: $ENV_FILE"
  echo "use --rotate to replace the local passwords"
else
  tmp=$(mktemp "$LOCAL_DIR/debug-accounts.env.tmp.XXXXXX")
  {
    echo "# Generated by scripts/dev-debug-accounts.sh for local development only."
    echo "# Do not commit. Values are also encrypted to $AGE_FILE."
    echo "PAIMOS_DEBUG_ACCOUNTS=1"
    echo "PAIMOS_DEBUG_SUPERADMIN_PASSWORD='$(password)'"
    echo "PAIMOS_DEBUG_ADMIN_PASSWORD='$(password)'"
    echo "PAIMOS_DEBUG_USER_PASSWORD='$(password)'"
    echo "PAIMOS_DEBUG_CUSTOMER_PASSWORD='$(password)'"
  } > "$tmp"
  mv "$tmp" "$ENV_FILE"
  chmod 600 "$ENV_FILE"
fi

tmp_age=$(mktemp "$LOCAL_DIR/debug-accounts.env.age.tmp.XXXXXX")
age -r "$recipient" -o "$tmp_age" "$ENV_FILE"
mv "$tmp_age" "$AGE_FILE"
chmod 600 "$AGE_FILE"

cat <<EOF
debug account env ready:
  plaintext: $ENV_FILE
  encrypted: $AGE_FILE

accounts:
  debug-superadmin
  debug-admin
  debug-user
  debug-customer

passwords were generated/stored locally and were not printed.
EOF
