//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/markus-barta/paimos/backend/handlers"
)

func main() {
	root, err := os.Getwd()
	if err != nil {
		fatal(err)
	}
	if filepath.Base(root) == "backend" {
		root = filepath.Dir(root)
	}
	outPath := filepath.Join(root, "frontend", "src", "types", "generated", "schema.ts")
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		fatal(err)
	}
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Generated by scripts/generate-frontend-schema.go; do not edit by hand.")
	fmt.Fprintf(&b, "// Source: backend/handlers.Schema v%s.\n\n", handlers.SchemaVersion)

	writeConst(&b, "ISSUE_STATUSES", handlers.Schema.Enums["status"])
	fmt.Fprintln(&b, "export type IssueStatus = typeof ISSUE_STATUSES[number]\n")
	writeConst(&b, "ISSUE_PRIORITIES", handlers.Schema.Enums["priority"])
	fmt.Fprintln(&b, "export type IssuePriority = typeof ISSUE_PRIORITIES[number]\n")
	writeConst(&b, "ISSUE_TYPES", handlers.Schema.Enums["type"])
	fmt.Fprintln(&b, "export type IssueType = typeof ISSUE_TYPES[number]\n")
	writeConst(&b, "RELATION_TYPES", handlers.Schema.Enums["relation"])
	fmt.Fprintln(&b, "export type RelationType = typeof RELATION_TYPES[number]\n")
	writeConst(&b, "TAG_COLORS", handlers.Schema.Enums["tag_colors"])
	fmt.Fprintln(&b, "export type TagColor = typeof TAG_COLORS[number]\n")
	writeConst(&b, "KNOWLEDGE_TYPES", handlers.Schema.Enums["knowledge_types"])
	fmt.Fprintln(&b, "export type KnowledgeType = typeof KNOWLEDGE_TYPES[number]\n")
	writeConst(&b, "KNOWLEDGE_STATUSES", handlers.Schema.Enums["knowledge_status"])
	fmt.Fprintln(&b, "export type KnowledgeStatus = typeof KNOWLEDGE_STATUSES[number]\n")

	keys := make([]string, 0, len(handlers.Schema.EnumFields))
	for k := range handlers.Schema.EnumFields {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	fmt.Fprintln(&b, "export const ENUM_FIELDS = {")
	for _, k := range keys {
		fmt.Fprintf(&b, "  %q: %q,\n", k, handlers.Schema.EnumFields[k])
	}
	fmt.Fprintln(&b, "} as const\n")

	if err := os.WriteFile(outPath, b.Bytes(), 0o644); err != nil {
		fatal(err)
	}
}

func writeConst(b *bytes.Buffer, name string, values []string) {
	fmt.Fprintf(b, "export const %s = [\n", name)
	for _, value := range values {
		fmt.Fprintf(b, "  %q,\n", value)
	}
	fmt.Fprintln(b, "] as const")
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, strings.TrimSpace(err.Error()))
	os.Exit(1)
}
